import  turtle
johny = turtle.Turtle()
johny.shape("turtle")
johny.pensize(10)
johny.color("red")
johny.circle(50)
johny.left(90)
johny.color("green")
johny.circle(50)
johny.left(90)
johny.color("blue")
johny.circle(50)
johny.left(90)
johny.color("yellow")
johny.circle(50)
turtle.done()